Repository googleapis/python-video-stitcher, pull requests merged in 2022-10, with the labels that each got.

#86 docs(samples): Fix Video Stitcher region tag prefix
  samples/snippets/create_cdn_key.py
  samples/snippets/create_live_session.py
  samples/snippets/create_slate.py
  samples/snippets/create_vod_session.py
  samples/snippets/delete_cdn_key.py
  samples/snippets/delete_slate.py
  samples/snippets/get_cdn_key.py
  samples/snippets/get_live_ad_tag_detail.py
  samples/snippets/get_live_session.py
  samples/snippets/get_slate.py
  samples/snippets/get_vod_ad_tag_detail.py
  samples/snippets/get_vod_session.py
  samples/snippets/get_vod_stitch_detail.py
  samples/snippets/list_cdn_keys.py
  samples/snippets/list_live_ad_tag_details.py
  samples/snippets/list_slates.py
  samples/snippets/list_vod_ad_tag_details.py
  samples/snippets/list_vod_stitch_details.py
  samples/snippets/update_cdn_key.py
  samples/snippets/update_slate.py
Labels: samples, api: videostitcher, size: m

#88 docs: update github repo url
  setup.py
Labels: size: xs

#91 fix(deps): allow protobuf 3.19.5
  setup.py
  testing/constraints-3.7.txt
Labels: api: videostitcher, size: xs
